language: objective-c
osx_image: xcode8.3

env:
  - PLATFORM=Mac  DESTINATION='platform=OS X'
  - PLATFORM=iOS  DESTINATION='platform=iOS Simulator,name=iPhone 7'

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -workspace JAMFKit.xcworkspace -scheme JAMFKit -destination "$DESTINATION" build-for-testing test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JAMFKit'
