os: osx
language: objective-c
osx_image: xcode9.2

env:
  global:
    - WORKSPACE="JamfKit.xcworkspace"
  matrix:  
    - PLATFORM="macOS" SCHEME="JamfKit macOS" DESTINATION="arch=x86_64" 
    - PLATFORM="iOS" SCHEME="JamfKit iOS" DESTINATION='platform=iOS Simulator,name=iPhone 8'

before_install:
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JamfKit'
