language: objective-c
osx_image: xcode8.3

env:
  - ACTION=test  PLATFORM=macOS     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 7'

script:
  - set -o pipefail && xcodebuild -scheme JAMFKit -destination "$DESTINATION" $ACTION | xcpretty
