os: osx
language: objective-c
osx_image: xcode8.3

env:
  global:
    - WORKSPACE="JAMFKit.xcworkspace"
  matrix:  
    - PLATFORM="macOS" SCHEME="JAMFKit macOS" DESTINATION="arch=x86_64" 
    - PLATFORM="iOS" SCHEME="JAMFKit iOS" DESTINATION='platform=iOS Simulator,name=iPhone 7'

before_install:
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'JAMFKit'
