language: objective-c
osx_image: xcode8.3
xcode_workspace: JAMFKit.xcworkspace
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="JAMFKit iOS"
  - MACOS_FRAMEWORK_SCHEME="JAMFKit macOS"
